package com.winning.batjx.core.app.mapper;

import com.winning.batjx.core.khgl.khwj.domain.Sjtb;

import java.util.List;

public interface SjtbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qyjx_sjtb
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qyjx_sjtb
     *
     * @mbg.generated
     */
    int insert(Sjtb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qyjx_sjtb
     *
     * @mbg.generated
     */
    Sjtb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qyjx_sjtb
     *
     * @mbg.generated
     */
    List<Sjtb> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qyjx_sjtb
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sjtb record);
}