package com.winning.batjx.core.khgl.khwj.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Sjtb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.dxlx
     *
     * @mbg.generated
     */
    private String dxlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.dxmc
     *
     * @mbg.generated
     */
    private String dxmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.dxbm
     *
     * @mbg.generated
     */
    private String dxbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.zbmc
     *
     * @mbg.generated
     */
    private String zbmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.zbbm
     *
     * @mbg.generated
     */
    private String zbbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.khnf
     *
     * @mbg.generated
     */
    private String khnf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.khzq
     *
     * @mbg.generated
     */
    private Integer khzq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.khpl
     *
     * @mbg.generated
     */
    private Integer khpl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.cjz
     *
     * @mbg.generated
     */
    private BigDecimal cjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.zbz
     *
     * @mbg.generated
     */
    private BigDecimal zbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.zbzt
     *
     * @mbg.generated
     */
    private Integer zbzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.cjlx
     *
     * @mbg.generated
     */
    private Integer cjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.czr
     *
     * @mbg.generated
     */
    private String czr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.czsj
     *
     * @mbg.generated
     */
    private Date czsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.bz
     *
     * @mbg.generated
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.jgbm
     *
     * @mbg.generated
     */
    private String jgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.faid
     *
     * @mbg.generated
     */
    private Integer faid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qyjx_sjtb.ssksbm
     *
     * @mbg.generated
     */
    private String ssksbm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.id
     *
     * @return the value of qyjx_sjtb.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.id
     *
     * @param id the value for qyjx_sjtb.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.dxlx
     *
     * @return the value of qyjx_sjtb.dxlx
     *
     * @mbg.generated
     */
    public String getDxlx() {
        return dxlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.dxlx
     *
     * @param dxlx the value for qyjx_sjtb.dxlx
     *
     * @mbg.generated
     */
    public void setDxlx(String dxlx) {
        this.dxlx = dxlx == null ? null : dxlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.dxmc
     *
     * @return the value of qyjx_sjtb.dxmc
     *
     * @mbg.generated
     */
    public String getDxmc() {
        return dxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.dxmc
     *
     * @param dxmc the value for qyjx_sjtb.dxmc
     *
     * @mbg.generated
     */
    public void setDxmc(String dxmc) {
        this.dxmc = dxmc == null ? null : dxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.dxbm
     *
     * @return the value of qyjx_sjtb.dxbm
     *
     * @mbg.generated
     */
    public String getDxbm() {
        return dxbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.dxbm
     *
     * @param dxbm the value for qyjx_sjtb.dxbm
     *
     * @mbg.generated
     */
    public void setDxbm(String dxbm) {
        this.dxbm = dxbm == null ? null : dxbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.zbmc
     *
     * @return the value of qyjx_sjtb.zbmc
     *
     * @mbg.generated
     */
    public String getZbmc() {
        return zbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.zbmc
     *
     * @param zbmc the value for qyjx_sjtb.zbmc
     *
     * @mbg.generated
     */
    public void setZbmc(String zbmc) {
        this.zbmc = zbmc == null ? null : zbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.zbbm
     *
     * @return the value of qyjx_sjtb.zbbm
     *
     * @mbg.generated
     */
    public String getZbbm() {
        return zbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.zbbm
     *
     * @param zbbm the value for qyjx_sjtb.zbbm
     *
     * @mbg.generated
     */
    public void setZbbm(String zbbm) {
        this.zbbm = zbbm == null ? null : zbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.khnf
     *
     * @return the value of qyjx_sjtb.khnf
     *
     * @mbg.generated
     */
    public String getKhnf() {
        return khnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.khnf
     *
     * @param khnf the value for qyjx_sjtb.khnf
     *
     * @mbg.generated
     */
    public void setKhnf(String khnf) {
        this.khnf = khnf == null ? null : khnf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.khzq
     *
     * @return the value of qyjx_sjtb.khzq
     *
     * @mbg.generated
     */
    public Integer getKhzq() {
        return khzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.khzq
     *
     * @param khzq the value for qyjx_sjtb.khzq
     *
     * @mbg.generated
     */
    public void setKhzq(Integer khzq) {
        this.khzq = khzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.khpl
     *
     * @return the value of qyjx_sjtb.khpl
     *
     * @mbg.generated
     */
    public Integer getKhpl() {
        return khpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.khpl
     *
     * @param khpl the value for qyjx_sjtb.khpl
     *
     * @mbg.generated
     */
    public void setKhpl(Integer khpl) {
        this.khpl = khpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.cjz
     *
     * @return the value of qyjx_sjtb.cjz
     *
     * @mbg.generated
     */
    public BigDecimal getCjz() {
        return cjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.cjz
     *
     * @param cjz the value for qyjx_sjtb.cjz
     *
     * @mbg.generated
     */
    public void setCjz(BigDecimal cjz) {
        this.cjz = cjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.zbz
     *
     * @return the value of qyjx_sjtb.zbz
     *
     * @mbg.generated
     */
    public BigDecimal getZbz() {
        return zbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.zbz
     *
     * @param zbz the value for qyjx_sjtb.zbz
     *
     * @mbg.generated
     */
    public void setZbz(BigDecimal zbz) {
        this.zbz = zbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.zbzt
     *
     * @return the value of qyjx_sjtb.zbzt
     *
     * @mbg.generated
     */
    public Integer getZbzt() {
        return zbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.zbzt
     *
     * @param zbzt the value for qyjx_sjtb.zbzt
     *
     * @mbg.generated
     */
    public void setZbzt(Integer zbzt) {
        this.zbzt = zbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.cjlx
     *
     * @return the value of qyjx_sjtb.cjlx
     *
     * @mbg.generated
     */
    public Integer getCjlx() {
        return cjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.cjlx
     *
     * @param cjlx the value for qyjx_sjtb.cjlx
     *
     * @mbg.generated
     */
    public void setCjlx(Integer cjlx) {
        this.cjlx = cjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.czr
     *
     * @return the value of qyjx_sjtb.czr
     *
     * @mbg.generated
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.czr
     *
     * @param czr the value for qyjx_sjtb.czr
     *
     * @mbg.generated
     */
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.czsj
     *
     * @return the value of qyjx_sjtb.czsj
     *
     * @mbg.generated
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.czsj
     *
     * @param czsj the value for qyjx_sjtb.czsj
     *
     * @mbg.generated
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.bz
     *
     * @return the value of qyjx_sjtb.bz
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.bz
     *
     * @param bz the value for qyjx_sjtb.bz
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.jgbm
     *
     * @return the value of qyjx_sjtb.jgbm
     *
     * @mbg.generated
     */
    public String getJgbm() {
        return jgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.jgbm
     *
     * @param jgbm the value for qyjx_sjtb.jgbm
     *
     * @mbg.generated
     */
    public void setJgbm(String jgbm) {
        this.jgbm = jgbm == null ? null : jgbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.faid
     *
     * @return the value of qyjx_sjtb.faid
     *
     * @mbg.generated
     */
    public Integer getFaid() {
        return faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.faid
     *
     * @param faid the value for qyjx_sjtb.faid
     *
     * @mbg.generated
     */
    public void setFaid(Integer faid) {
        this.faid = faid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qyjx_sjtb.ssksbm
     *
     * @return the value of qyjx_sjtb.ssksbm
     *
     * @mbg.generated
     */
    public String getSsksbm() {
        return ssksbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qyjx_sjtb.ssksbm
     *
     * @param ssksbm the value for qyjx_sjtb.ssksbm
     *
     * @mbg.generated
     */
    public void setSsksbm(String ssksbm) {
        this.ssksbm = ssksbm == null ? null : ssksbm.trim();
    }
}